apiVersion: v1
kind: Service
metadata:
  name: reporter-server
  labels:
    name: reporter-server
    tier: server
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 443
      protocol: TCP
      name: http
  selector:
    name: reporter-server
    tier: server
